### PR TITLE
Assorted improvements

### PR DESCRIPTION
**Pull request by grenzr**
This PR adds quite a few bits of new functionality and refactor (some of which might be a step too far for you, but I thought I'd give it a go anyway :)

- chart renamed to vsts-agent instead of helm-vsts-agent
- make helm-package task added to create package (can now use` helm repo add vsts-agent https://raw.githubusercontent.com/grenzr/helm-vsts-agent/assorted_improvements/charts/` to pull in the repo)
- add extraEnv variable to add more env vars into the vsts-agent container
- add cleanRun which resets vsts-agent container upon completion of each build (resets the working environment)
- add extraContainers variable which allows sidecar of additional containers into the vsts-agent pod
- add volumes/volumeMounts variable which allows ability to mount arbitrary volumes into the vsts-agent container or elesewhere in the pod

Our example use is to sidecar our own docker DIND image instead of using the k8s hosts docker service (which imo is not a good approach). This way guarantees consistency from k8s deployment to deployment :

```
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

cleanRun: true

extraEnv:
  DOCKER_HOST: tcp://localhost:2375

extraContainers:
- name: dind-daemon
  image: docker:18.05.0-dind
  args: ["--mtu=1450"]
  resources:
    requests:
      memory: 1Gi
  securityContext:
      privileged: true
  volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker

volumes:
- name: docker-graph-storage
  emptyDir: {}

volumeMounts: []
```

### CODE REVIEW

**Comment by vglafirov** [comment]
@grenzr Please rebase to master

**Comment by vglafirov** [comment]
@grenzr Thanks for your PR. It might take a while to test your changes.

**Comment by grenzr** [comment]
Hi @vglafirov I will look at rebasing shortly

**Comment by grenzr** [comment]
Ok, its rebased now, but the 1.0.0 tgz doesn't currently contain the storageclass changes.. I could do it as part of the PR if you like (since I've put one there in this PR), but I think going forward it would probably be best you cut your own tgz's after merging 1 or many PRs when you're ready to declare a new release.

**Comment by grenzr** [comment]
I have another commit behind this, in a different branch, which allows you to provide your own additional volumeClaimTemplates too.

https://github.com/grenzr/helm-vsts-agent/commit/e84b07820ffd8734f986454dcb0099e6501741e3

Can pull it in this PR too if you want? (This also has a newly built 1.0.0 tgz)
Or can deal with it in a separate PR.. up to you.

**Pull request merged**
